stages:
  visualize_data:
    cmd: python src/data_visualization.py
    deps:
      - src/data_visualization.py
      - data/raw/bank-additional-full.csv
    outs:
      - docs/figures/distribucion_target.png
      - docs/figures/distribucion_education.png
      - docs/figures/distribucion_edad.png
      - docs/figures/correlaciones_numericas.png
      - docs/figures/tasa_suscripcion_education.png
      - docs/figures/tasa_suscripcion_mes.png
      - docs/figures/reporte_dataset.html

  test_data_quality:
    cmd: pytest test/test_data_quality.py --html=docs/test_results/results.html --self-contained-html --junitxml=docs/test_results/results.xml > docs/test_results/results.txt
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
    outs:
      - docs/test_results/results.html
      - docs/test_results/results.xml
      - docs/test_results/results.txt